### ISSUE TITLE
Merge to the upsteam all the components (12/2021)

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#149]
Make a merge with the latest version of NCB0 components : 

- [x] Merge UI (v 6.5.1) https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/12
- [x] Merge API (v 5.22.0) https://github.com/ontoportal-lirmm/ontologies_api/issues/3
- [x] Merge ontologies_linked_data (v 5.22.1) https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/3
- [x] Merge goo (v 5.22.1) https://github.com/ontoportal-lirmm/goo/issues/2
- [x] Merge ncbo_cron (v 5.22.1) https://github.com/ontoportal-lirmm/ncbo_cron/issues/2
- [x] Merge ontologies_api_ruby_client https://github.com/ontoportal-lirmm/ontologies_api_ruby_client/issues/1
- [ ] Merge owlapi_warapper
- [x] Merge ncbo_annotator https://github.com/agroportal/documentation/issues/158
- [x] Remove sparqlclient #166

**Comment by syphax-bouazzouni** [comment]
Merge owlapi_wrapper transferred to the next release
