### ISSUE TITLE
Problem updating STY (and NCBITAXON) even with a valid pullLocation

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#177]
As discussed in #172 STY is not processed by the automatic ontology pull. 

Still it has a valid pullLocation : 
http://data.agroportal.lirmm.fr/ontologies/STY/submissions/1?display=pullLocation

It seems the ontology is ignored by the script

**Comment by jonquet** [comment]
This issue also concerns now NCBITAXON which has been explicitly connected with a pullLocation.

Discussion with @syphax-bouazzouni informed on the fact that a flag "enable_pull_umls" is set to false in the ncbo_cron project by default.

- [x] change the falg and retest

**Comment by syphax-bouazzouni** [comment]
## Todo 
- [x] https://github.com/ontoportal-lirmm/ncbo_cron/issues/5
## Did it work ?
#### Is umls pull enabled
yes, like the below screenshot ( of the scheduler-pull.log of the 24th January) shows 
![image](https://user-images.githubusercontent.com/29259906/151150619-366333f2-182d-41de-afa2-44d52e042c5a.png)
### Parsing erros
new file detected but can't parse, see below an example of what we can see in the scheduler-pull.log of the 24th January for STY
![image](https://user-images.githubusercontent.com/29259906/151151667-0bfe23e6-2015-4a56-9cb9-78223821b610.png)

- [x] STY, 
- [ ] https://github.com/agroportal/documentation/issues/191

**Comment by syphax-bouazzouni** [comment]
I did an update of STY version manually in the console "ncbo_cron --console", just to test if it's a parsing error.
So it's not a parsing matter, more a bug in the code to find .
