### ISSUE TITLE
Update browse page

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#182]
## Todo : 
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/20
- [x] https://github.com/ontoportal-lirmm/ontologies_api/issues/5
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/28
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/32

## Deploy on production : 

- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/42

## Do Pull request : 
- [x] #183

## Related 

- https://github.com/ncbo/bioportal_web_ui/pull/184
