### ISSUE TITLE
Update our triple store to a new one (Alegrograph, Virtuoso or Graph DB)

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#229]
## Context
Currently, we are using 4store as our triple store (database), but it is no longer maintained and we have a lot of issues  because of it (see https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/8)

## Goal

- Move from out from 4store to another triple store, either: Algrograph, Virtuoso or Graph DB 

## Roadmap  

- [x] https://github.com/ontoportal-lirmm/goo/pull/48
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/106
- [x] https://github.com/ontoportal-lirmm/ontologies_api/pull/54
- [x] Choose one of those Stores 
- [x] #607
- [x] Test it at https://testportal.lirmm.fr/ for 2 weeks
- [x] Test it at https://stageportal.lirmm.fr/ for 2 weeks 
- [x] Deploy it in production in the Q4 of 2024

## Documentation

- [Replacing 4store with AllegroGraph ontoportal guide](https://ontoportal.github.io/administration/steps/allegrograph_configuration/)
- [Allegrograph configuration]( https://ontoportal.github.io/administration/steps/allegrograph_configuration)
- [Data Migration](https://github.com/ncbo/ontoportal_utilities/tree/master/4store) config and  for the automatic 
- https://docs.openlinksw.com/virtuoso/
- https://graphdb.ontotext.com/documentation/10.0/

**Comment by syphax-bouazzouni** [comment]
update to AllegroGraph, see https://ontoportal.github.io/administration/steps/allegrograph_configuration/ for the config and  https://github.com/ncbo/ontoportal_utilities/tree/master/4store for the automatic data migration

**Comment by syphax-bouazzouni** [comment]
For mappings may be think to use Log4j

**Comment by syphax-bouazzouni** [comment]
to do before https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/37

**Comment by syphax-bouazzouni** [comment]
Done  for AgroPortal and BiodivPortal in https://github.com/ontoportal-lirmm/ontologies_api/pull/119
