### ISSUE TITLE
Add system service for mgrep-lem and add it to opstart

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#243]
## The service to add (inspired by the existent mgrep.service)
```bash
[Unit]
Description=mgrep server running on port 55557
After=network.target

[Service]
Type=forking
ExecStart=/usr/local/mgrep/mgrep --port=55557 -f /srv/ontoportal/data/mgrep/dictionary/dictionary-lem.txt -w /usr/local/mgrep/word_divider.txt -c /usr/local/mgrep/CaseFolding.txt
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=mgrep-lem
User=mgrep
Group=ontoportal
PermissionsStartOnly=false
TimeoutStopSec=10

[Install]
WantedBy=multi-user.target
```

## Todo

- [x] cd /etc/systemd/system
- [x] cp mgrep.service mgrep-lem.service
- [x] nano mgrep-lem.service (and copy the service content described below)
- [x] systemctl enable mgrep-lem.service
- [x] nano /usr/local/bin/opstart (add the line `mgrep-lem.service`)
- [x] nano /usr/local/bin/opstop (add the line `mgrep-lem.service`)
- [x] nano /usr/local/bin/opstatus  (add the line `mgrep-lem.service`)
- [x] sudo oprestart

## Result

```bash
[root@agroportal system]# sudo opstatus
4s-boss.service                     active
4s-backend.service                  active
4s-httpd.service                    active
tomcat.service                      active
redis-server-goo.service            active
redis-server-http.service           active
redis-server-persistent.service     active
mgrep.service                       active
mgrep-lem.service                   active
memcached.service                   active
solr.service                        active
ncbo_cron.service                   active
unicorn.service                     active
nginx.service                       active
httpd.service                       active
```

## Deployed in 

- [x] Agroportal
- [x] Bioportal
- [x] Stageportal (after updating the API configs)
- [x] Testportal (after updating the API configs)
