### ISSUE TITLE
Refactor/fix notification

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#257]
the continuation of https://github.com/agroportal/documentation/issues/151
# TODO / TO FIX
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/4
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/21
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/8
- [x] do a PL for NCBO : https://github.com/ncbo/ontologies_linked_data/pull/148/

**Comment by jonquet** [comment]
In complement, we 'are going to change the UI to enable users/onto-admin to subscribe to notifications. 

### ADMINS
If agroportal-support is setup to receive all notifications then by default AgroPortal admins (admin role) should not be registered to any notifications. We rely on the email alias which allows us to decide which users will received all the notifications or not.

### ONTOLOGY-ADMIN

- [ ] Make an admin by default subsrbie to all notification of its ontology
- [ ] Remove subscription box form Edit Ontology Information page
<img width="496" alt="image" src="https://user-images.githubusercontent.com/7379183/163077483-558099ee-2f4b-4ed6-8e6e-c8dee388d9b9.png">
This box is useless. If someone submit an ontology or can access this page it means that they are admin of the ontology, so another UI will support this in the Account Settings page

### ONTOLOGY-ADMIN and USERS

- [ ] By default ontology admin should be automatically subscribed to ALL (notes and processing)  notifications. As well as remote pull failure. Remote pull failure shall not be removable. 

- [ ] The Summary page for an ontology should include a "Subscribe" button to activate the notifications for a logged-in user for the current ontologies. If not logged in this mus direct to login page.
The idea is to add an icon (in another colour e.g., yellow of the FAIR score) to activate notifications with a setting to ALL (notes and processing) by default. 
<img width="267" alt="image" src="https://user-images.githubusercontent.com/7379183/163078402-c7063908-d474-4778-b8a3-f762aab51368.png">

- [ ] The Account Settings page should be updated to refine the way one see/change his/her subscriptions (either activated by being admin of an ontology or by the subscription button cited above).
<img width="337" alt="image" src="https://user-images.githubusercontent.com/7379183/163077836-fbe18fa9-c81c-4292-9130-7c31ef9d4aad.png">
Keeping a table approach, one should see in columns a way to subscribe either to notes, processing or both (all).
As lines in the tables: 
- All the ontologies that the user have activated with a "follow" button on the Summary page
- All the ontologies for which a user is admin

**Comment by syphax-bouazzouni** [comment]
To be continued here https://github.com/agroportal/project-management/issues/260
