### ISSUE TITLE
Push our data to the  LOD Cloud

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#275]
### Todo

- [ ] In the backend add an endpoint `/ontologies?format=lod-cloud` that will show the lod-cloud JSON format of our data
- [x] Add the correct value to the includeInDataCatalog property 
- [ ] Use the includeInDataCatalog property to filter only the ones that are not in LOD `filter_by=includeInDataCatalog&filter_value=”lod” `
- [ ] In the generated links, if a link to a LOD-CLOUD  dataset is found use their ID instead of ours
- [ ] Submit the generated JSON
- [ ] Generate a D2KAB Cloud with https://github.com/lod-cloud/lod-cloud-draw

**Comment by jonquet** [comment]
Clement TODO: manualy lookup the ontologies in AgroPortal already present in the LOD cloud (e.g., TAXREF, GO) and save this info in the metadata property includedInDataCatalog.

@syphax-bouazzouni Will use this to filter out the list of ontologies returned in the lod-cloud format.

**Comment by jonquet** [comment]
I have manually reviewed the resources currently in AgroPortal that are in the LOD Cloud. I have found : 

AGROVOC => https://lod-cloud.net/dataset/agrovoc
BFO => https://lod-cloud.net/dataset/bioportal-bfo
BT => https://lod-cloud.net/dataset/bioportal-bt
CL => https://lod-cloud.net/dataset/bioportal-cl
CPC => https://lod-cloud.net/dataset/cpc-2008
CDAO => https://lod-cloud.net/dataset/bioportal-cdao
ENVO => https://lod-cloud.net/dataset/bioportal-envo
EFO => https://lod-cloud.net/dataset/bioportal-efo
GO => https://lod-cloud.net/dataset/bioportal-go_x2
GEMET => https://lod-cloud.net/dataset/gemet
GACS => https://lod-cloud.net/dataset/GACS
NCBITAXON => https://lod-cloud.net/dataset/bioportal-ncbitaxon
PATO => https://lod-cloud.net/dataset/bioportal-pato
PO => https://lod-cloud.net/dataset/bioportal-po_x2
TO => https://lod-cloud.net/dataset/bioportal-to
PR => https://lod-cloud.net/dataset/bioportal-pr
SIO => https://lod-cloud.net/dataset/bioportal-sio
SO => https://lod-cloud.net/dataset/bioportal-so_x1
SNPO => https://lod-cloud.net/dataset/bioportal-snpo
SPTO => https://lod-cloud.net/dataset/bioportal-spto
SOY => https://lod-cloud.net/dataset/bioportal-soy
SDGIO => https://lod-cloud.net/dataset/SDG
TAXREF-LD => https://lod-cloud.net/dataset/taxref-ld
OBOE => https://lod-cloud.net/dataset/bioportal-oboe
VT => https://lod-cloud.net/dataset/bioportal-vt


FYI: attention the ID at lod-cloud.net are case sensitive.

**Comment by syphax-bouazzouni** [comment]
@jonquet no more in the plans?

**Comment by jonquet** [comment]
With the end of D2KAB this issue is not much relevant anymore. Maybe the context of OntPortla federation will be appropriate.
Plus the exchanges with the LOD Could folks were not very productive. If we re-open this issue, we would need to be sure we will have support from them. 
The LOD Cloud has been updated once a year in the last 4 years.
