### ISSUE TITLE
AGROVOC metadata can't be updated

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#286]
## Trying to do
```
PATCH
http://data.agroportal.lirmm.fr/ontologies/AGROVOC/submissions/23
{
  	“released” : “1980-01-01",
	“modificationDate” : “2022-05-01T00:00:00+00:00",
	“version” : “2022-05"
}
PATCH
http://data.agroportal.lirmm.fr/ontologies/AGROVOC/submissions/24
{
  	“released” : “1980-01-01",
	“modificationDate” : “2022-06-01T00:00:00+00:00",
	“version” : “2022-06"
}
PATCH
http://data.agroportal.lirmm.fr/ontologies/AGROVOC/submissions/19
{
	“version” : “2022-03"
}
PATCH
http://data.agroportal.lirmm.fr/ontologies/AGROVOC/submissions/20
{
	“version” : “2022-04"
}

PATCH
http://data.agroportal.lirmm.fr/ontologies/AGROVOC/submissions/24
{
  	“pullLocation”: “http://agrovoc.uniroma2.it/latestAgrovoc/agrovoc_lod.nt.zip”
}

```

## Issue

These requests returns 

![Image](https://user-images.githubusercontent.com/29259906/176851619-0c6bf59f-d956-4cc4-b680-acf20c9593c7.png)

## Log

```
[Fri Jul 01 09:46:43.676036 2022] [proxy_http:error] [pid 19148:tid 140094233073408] (70007)The timeout specified has expired: [client 172.30.3.166:57333] AH01102: error reading status line from remote server agroportal.lirmm.fr:8080
[Fri Jul 01 09:46:43.676286 2022] [proxy:error] [pid 19148:tid 140094233073408] [client 172.30.3.166:57333] AH00898: Error reading from remote server returned by /ontologies/AGROVOC/submissions/23
```

**So it's a timeout issue**

**Comment by syphax-bouazzouni** [comment]
Fixed with https://github.com/agroportal/project-management/issues/289

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/29259906/180753019-30928af6-5525-4986-b7be-0702b64f8ecc.png">

## Todo 


- [x] Update http://data.agroportal.lirmm.fr/ontologies/AGROVOC/submissions/23
- [x] Update  http://data.agroportal.lirmm.fr/ontologies/AGROVOC/submissions/24
- [x] Update http://data.agroportal.lirmm.fr/ontologies/AGROVOC/submissions/19
- [x] Update http://data.agroportal.lirmm.fr/ontologies/AGROVOC/submissions/20
- [x] Update http://data.agroportal.lirmm.fr/ontologies/AGROVOC/submissions/24 pullLocation
