### ISSUE TITLE
Optimize GOO for ressource that have a lot of attribute as list

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#289]
## Related issues

- https://github.com/agroportal/project-management/issues/271
- https://github.com/agroportal/project-management/issues/286
- https://github.com/agroportal/project-management/issues/280
- https://github.com/ontoportal-lirmm/goo/pull/3
- https://github.com/agroportal/project-management/issues/235

## TODO

- [x] Document GOO => https://doc.jonquetlab.lirmm.fr/share/a476a690-722d-40bc-accd-8d56eef91590
- [X] Implement the new paradigm of fetching attributes values and do a PR (https://github.com/ncbo/goo/pull/124)
- [X] Merge with our code (to add the language preference) (https://github.com/ontoportal-lirmm/goo/commit/835aefa458186485eef60d3845315c478a95ff23)

#### Testportal
- [x] CRON
- [x] API

#### Stageportal
- [x] CRON
- [x] API

#### Agroportal
- [x] CRON
- [x] API

#### Bioportal
- [x] CRON
- [x] API
