### ISSUE TITLE
SSSOM loader

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#292]
## Requirements

- https://github.com/agroportal/project-management/issues/265

## Todo 

- [x] https://github.com/mapping-commons/sssom-py/pull/281
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/29
- [x] https://github.com/ontoportal-lirmm/owlapi_wrapper/issues/2
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/35
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/30
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/31
- [x] https://github.com/ncbo/ontologies_linked_data/pull/157
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/90
- [ ] Add an option to the Python SSSOM script to convert+import in Ontoportal

**Comment by syphax-bouazzouni** [comment]
A possible use case for the next iteration is FCU-TAXRET, the TSV is attached to this comment
[FCU_TAXREF-LD_mappings_20230314.csv](https://github.com/agroportal/project-management/files/11002206/FCU_TAXREF-LD_mappings_20230314.csv)
