### ISSUE TITLE
Mapping UI refactor

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#299]
## TODO

- [x] https://github.com/ncbo/bioportal_web_ui/pull/225

### Migration to Hotwire 

- [x] Migrate and remove bp_create_mappings.js.erb  (500 lines less)

### In concept page
- [x] Remove the button "create an external mapping"
- [x] Merge the external form with the base(normal)  mapping form
- [x] Add form validation to the mapping creation form
- [x] Add the possibility to edit a mapping
- [x] update mapping delete (from batch delete to individual)

### In mapping page 

- [x] https://github.com/ncbo/bioportal_web_ui/pull/209
- [x] Add the possibility to create mapping with a source and target class
- [x] Add the possibility to search the mappings of a class
- [ ] Add the possibility to search the mappings between two classes

**Comment by syphax-bouazzouni** [comment]
Note for the form validation of the mappings creation/edition, the problem was that in the API there were not validation implemented. For now what i did is just a temporary validation in the UI (follow up https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/41).
