### ISSUE TITLE
Extract ontology mappings (excatMatch,...)

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#302]
### Requirement

 If inside the class/concepts defintion are defined mapping relations (need to be defined and listed), we should extract them and add them to the mapping list of the class/concept.

Actually they are only showed the class/concept details 

![Image](https://user-images.githubusercontent.com/29259906/190163420-887d261d-9e21-4d35-9767-2bd7105f29fa.png)

### The proposed solution 
is to upgrade the SPARQL query used to fetch the mapping, defined in [ def self.mappings_ontologies(sub1, sub2, page, size, classId = nil, reload_cache = false) ](https://github.com/ontoportal-lirmm/ontologies_linked_data/blob/2e4f9c1c3debc144df317a6d777a58b90405f644/lib/ontologies_linked_data/mappings/mappings.rb#L188)

The request will go from 

```SQL

SELECT DISTINCT ?s1 ?s2 ?g ?source ?o
WHERE {
 {  
     GRAPH <http://data.bioontology.org/ontologies/E-PHY/submissions/1> {     
      ?s1 <http://bioportal.bioontology.org/ontologies/umls/cui> ?o .
     } 
     GRAPH ?g {      
       ?s2 <http://bioportal.bioontology.org/ontologies/umls/cui> ?o .  
     }  
     BIND ('CUI' AS ?source) 
 } 
 UNION 
 { 
     GRAPH <http://data.bioontology.org/ontologies/E-PHY/submissions/1> {
      ?s1 <http://data.bioontology.org/metadata/def/mappingSameURI> ?o .
     } 
     GRAPH ?g {
      ?s2 <http://data.bioontology.org/metadata/def/mappingSameURI> ?o .
     } 
     BIND ('SAME_URI' AS ?source 
} 
UNION
{  
    GRAPH <http://data.bioontology.org/ontologies/E-PHY/submissions/1> { 
     ?s1 <http://data.bioontology.org/metadata/def/mappingLoom> ?o .
    } 
    GRAPH ?g {
     ?s2 <http://data.bioontology.org/metadata/def/mappingLoom> ?o .
    }
    BIND ('LOOM' AS ?source)
 } 
 UNION 
 { 
    GRAPH <http://data.bioontology.org/ontologies/E-PHY/submissions/1> { 
     ?s1 <http://data.bioontology.org/metadata/def/mappingRest> ?o . 
	  } 
    GRAPH ?g {
     ?s2 <http://data.bioontology.org/metadata/def/mappingRest> ?o .  
    }  
    BIND ('REST' AS ?source)}
 }
 FILTER ((?s1 != ?s2) || (?source = 'SAME_URI'))
 FILTER (!STRSTARTS(str(?g),'http://data.bioontology.org/ontologies/E-PHY'))
} 
OFFSET 0 LIMIT 50

```

To 

```SQL

SELECT DISTINCT ?s1 ?s2 ?g ?source ?o
WHERE {
 {  
     GRAPH <http://data.bioontology.org/ontologies/E-PHY/submissions/1> {     
      ?s1 <http://bioportal.bioontology.org/ontologies/umls/cui> ?o .
     } 
     GRAPH ?g {      
       ?s2 <http://bioportal.bioontology.org/ontologies/umls/cui> ?o .  
     }  
     BIND ('CUI' AS ?source) 
 } 
 UNION 
 { 
     GRAPH <http://data.bioontology.org/ontologies/E-PHY/submissions/1> {
      ?s1 <http://data.bioontology.org/metadata/def/mappingSameURI> ?o .
     } 
     GRAPH ?g {
      ?s2 <http://data.bioontology.org/metadata/def/mappingSameURI> ?o .
     } 
     BIND ('SAME_URI' AS ?source 
} 
UNION
{  
    GRAPH <http://data.bioontology.org/ontologies/E-PHY/submissions/1> { 
     ?s1 <http://data.bioontology.org/metadata/def/mappingLoom> ?o .
    } 
    GRAPH ?g {
     ?s2 <http://data.bioontology.org/metadata/def/mappingLoom> ?o .
    }
    BIND ('LOOM' AS ?source)
 } 
 UNION 
 { 
    GRAPH <http://data.bioontology.org/ontologies/E-PHY/submissions/1> { 
     ?s1 <http://data.bioontology.org/metadata/def/mappingRest> ?o . 
	  } 
    GRAPH ?g {
     ?s2 <http://data.bioontology.org/metadata/def/mappingRest> ?o .  
    }  
    BIND ('REST' AS ?source)}
 }
 UNION 
 { 
    GRAPH <http://data.bioontology.org/ontologies/E-PHY/submissions/1> { 
     ?s1 <http://data.bioontology.org/metadata/def/mappingRest> ?o . 
	  } 
    GRAPH ?g {
     ?s2 <http://data.bioontology.org/metadata/def/mappingRest> ?o .  
    }  
    BIND ('REST' AS ?source)}
 }
UNION
{  
   GRAPH <http://data.bioontology.org/ontologies/E-PHY/submissions/1> {     
      ?s1 <http://www.w3.org/2004/02/skos/core#exactMatch> ?s2 .
     } 
     BIND( <http://data.bioontology.org/ontologies/E-PHY/submissions/1> as ?g)
     BIND( ?s2 AS ?o)
     BIND ('SKOS:EXACT_MATCH' AS ?source) 
 } 
 FILTER ((?s1 != ?s2) || (?source = 'SAME_URI'))
 FILTER (!STRSTARTS(str(?g),'http://data.bioontology.org/ontologies/E-PHY') || ((?source = 'SKOS:EXACT_MATCH')))
} 
OFFSET 0 LIMIT 50

```

## TODO

- [x] Define the list of mapping relation to extract
- [x] Update the SPARQL query
- [x] Test if it works

**Comment by syphax-bouazzouni** [comment]
## The list of mapping relation to extract (for now)

- skos:closeMatch
- skos:exactMatch
- skos:broadMatch
- skos:narrowMatch
- skos:relatedMatch

**Comment by jonquet** [comment]
Note for later : we will need to add alos: 
owl:sameAs and oboInOwl:hasDbXref has not.
