### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#307]
## References

- [JSON-LD String Internationalization](https://www.w3.org/TR/json-ld11/#string-internationalization)
- https://github.com/ncbo/goo/issues/95
- https://github.com/ncbo/goo/pull/118

## Goal

Make Ontoportal/Agroportal UI and API multilingual, where a user can decide on the language to display or show them all.

### Phase 1:  Read one language
 
Most of the work is done here 

- https://github.com/ontoportal-lirmm/goo/blob/master/lib/goo/sparql/solutions_mapper.rb#L75 for Agroportal
- And https://github.com/ontoportal/goo/blob/master/lib/goo/sparql/queries.rb#L752 for Bioportal

Currently, we filter data fetched from the triple store by only one language, English only for Bioportal and English or French for Agroportal.

This behavior is settled by a [constant (:EN)](https://github.com/ontoportal/goo/blob/master/lib/goo/sparql/queries.rb#L752) in Bioportal and an [Array of languages](https://github.com/ontoportal/goo/blob/master/lib/goo/sparql/queries.rb#L752) in Agroportal.

![image](https://user-images.githubusercontent.com/29259906/223521881-b4dce748-bb1e-4751-9e9c-9050382a88d0.png)

This first step is to do is to add the possibility of taking a request parameter `?lang` for language to show 

- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/63
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/165
- [x] https://github.com/agroportal/project-management/issues/309

### Phase 2: Read multiple lang (JSON-LD compliant)

Currently, we don't use the `lang` attribute of literals, i.e in source data, we have `skos:prefLabel "test"@en` but we show only "test" if we want to show multiple languages the language information needs to be used and be complainant with what JSON-LD specify 

The plan would is to be fully compliant JSON-LD and show the following in our API endpoints
<img width="822" alt="image" src="https://user-images.githubusercontent.com/29259906/213639312-a202f1ac-9c03-43e5-9698-835b8ec22e17.png">

- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/84
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/252

### Phase 3: write multiple languages

For a given metadata attribute (e.g description), how do we write in multiple languages (e.g have an English and French description)?

**Comment by syphax-bouazzouni** [comment]
Possible difficulties 

- The case of classes prefLabel, pre-filled in the parsing step 
-  Multilingual term indexation

**Comment by syphax-bouazzouni** [comment]
### INRAE DipSO requirements (Sophie Aubin and Sonia Bravo) 

Voici nos retours concernant le multilinguisme:

> Question de Clément (slack) sur l’affichage d’un concept lorsqu’il n’y a pas de libellé pour la langue sélectionnée. « On a besoin de decidion en terme de quoi faire quand il y a pas de concepts dans un langauge donnée... affiché l’URI ? la fin de l’URI ? un fallback language e.g. anglais ? etc ... »

Comme sur Skosmos, faire apparaître l’autre libellé pref en mettant entre parenthèse fr/en. Si pas de label, alors afficher la fin de l’URI (mais normalement ça n’arrive pas en SKOS)

> Le comportement quand on change de langue est cohérent entre concept / scheme / collection : OK
**Question : Est-ce que vous envisagez de traduire les noms des propriétés en français ?**


La fiche concept n’affiche pas les termes dans les autres langues que celle sélectionnée

Dans SKOSMOS
![image](https://user-images.githubusercontent.com/29259906/230158222-fea3d498-0f77-49c0-b8b2-f5516dc10806.png)

Vous pourriez ajouter un bloc « Labels » dans la seconde section, au-dessus de narrower (on veut voir ces termes dans d’autres langues assez rapidement, sans scroller trop)

On affiche toujours en 1er la langue d’affichage sélectionnée, si "EN"

<img width="283" alt="image" src="https://user-images.githubusercontent.com/29259906/230158541-d5d2ca5d-06ed-41df-bb90-1fa5b74b6ed5.png">

 
Idéalement, il faudra le même comportement pour les définitions (et autres notes). Afficher la def dans chaque langue en précisant la langue + affichage de la définition de la langue d’affichage en 1er.

**Comment by jonquet** [comment]
Hello @saubin78 . Ok pour ces 3 points principaux. 

- Pour le label fallback (si pas de label dans la langue explicitement choisie), je suis pas encore sur qu'il faut revenir a un label dans une autre langue. Pour moi c'est un peu en opposition avec le fait que qq a explicitement choisie une langue a afficher. 

- Pour l'affichage des autres langues de toutes les propriétés "traductions", nous ferons pas comme SKOSMOS la car sinon les pages seront tjrs aussi "lourdes et chargées" qq soit la langue sélectionnée puisque tout s'affichera. Ce que nous proposons est d'avoir une option "All language" dans le menu de selection de langue et dans ce cas cela affichera tout groupé: tous les pref labels, tous les syn, toutes les def, etc. En plus, c'est techniquement plus logique/efficace et donc beaucoup plus facile a faire.

- Pour la traduction des propriétés, bon point. Nous travaillons aussi a l'internationalization du portail (en Francais d'abord). Nous pourrons traduire les propriétés qui sont mappés au modele (celle du bloc du haut). Par contre celle du bloc du bas qui affiche directement le contenu de l'ontologie nous ne pourrons pas les traduire, il faudra que les ontologies définissent des rdfs:label pour les propriétés. C'est pas si frequent mais c'est mieux => essayer de le faire dans INRAETHES, cela nous sera utile pour tester.

**Comment by saubin78** [comment]
Pour la traduction des propriétés, bon point. Nous travaillons aussi a l'internationalization du portail (en Francais d'abord).

> je sais que l'INIST a travaillé sur l'internationalisation de VocBench mais je n'arrive pas à retrouver les données sur le https://bitbucket.org/art-uniroma2/vocbench3/src/master/ (je m'y prends peut-être mal)

**Comment by syphax-bouazzouni** [comment]
Deployed in production in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/240
From this project remains two tasks postponed for the future:

- https://github.com/agroportal/project-management/issues/309 in 2024 Q1 
- https://github.com/agroportal/project-management/issues/453
