### ISSUE TITLE
Fix Agroportal widgets

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#349]
### Goal

How can people re-use our UI tools (concepts/ontologies search, tree view, visualization) directly inside their web applications

### Use case
https://entrepot.recherche.data.gouv.fr/dataset.xhtml?persistentId=doi:10.57745/DEUATN&version=DRAFT

![Image](https://user-images.githubusercontent.com/29259906/211053249-1ff61eb8-2158-4e1e-b519-7be4da94c991.png)

In [Data INRAE](https://entrepot.recherche.data.gouv.fr/dataverse/inrae) we can replace the fields above with only one,  the concept search below 

https://user-images.githubusercontent.com/29259906/211053802-9299f926-0a70-49de-bcfa-b045f0994e53.mov

### TODO

- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/145
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/147
- [ ] Path to roos does not work for SKOS resources (e.g http://data.agroportal.lirmm.fr/ontologies/AGROVOC/classes/http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_24024/paths_to_root/)
- [ ] Are they still usable nowadays, if not how can we update them?

**Comment by syphax-bouazzouni** [comment]
@jvendetti, @graybeal are the widgets used by  Bioportal users? and any plans to update them?

**Comment by jvendetti** [comment]
Hi @syphax-bouazzouni - off the top of my head, I'm not aware of anyone specific that's using the widgets. We have some existing issues logged in bioportal_web_ui that detail some of the problems:

https://github.com/ncbo/bioportal_web_ui/issues/79
https://github.com/ncbo/bioportal_web_ui/issues/132
https://github.com/ncbo/bioportal_web_ui/issues/190

... and there's the separate issue tracker for the forked version of BioMixer:

https://github.com/ncbo/biomixer/issues

I've had some ideas about how to move forward on the widgets in the past, but fixing and updating them has never made it to the top of the priority list. I think it would be nice to modernize how they're developed, e.g., having a separate repository for each of the widgets so that we can take advantage of GitHub issue tracking, tagging, downloads, documentation (either via the README files or the built-in wikis), etc.

**Comment by syphax-bouazzouni** [comment]
Thanks, @jvendetti  for your response.

Just so you know, I did this https://github.com/ncbo/bioportal_web_ui/pull/242, it fixed the two first issues you pointed out.

I will see with @jonquet if this is a priority for us, and decide after (maybe an alliance subject)

**Comment by syphax-bouazzouni** [comment]
Related work https://github.com/SSHOC/dataverse-external-vocab-support/commit/b3368997b1db79fe26fb04318c4aa19bbe277528

And INRAE Dataverse https://github.com/IQSS/dataverse/pull/10145
