### ISSUE TITLE
add `deployer` user in the servers

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#400]
## Goal
see https://capistranorb.com/documentation/getting-started/authentication-and-authorisation/
## TODO

- [ ] Add deployer user in Stageportal
- [ ] Add deployer user in Agroportal
- [ ] Add deployer user in Bioportal
- [ ] Add deployer user in Testporta

**Comment by syphax-bouazzouni** [comment]
instead of creating a user `deployer`, we just use the `ontoportal` user.
