### ISSUE TITLE
Add keywords for our github repositories 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#442]
### TODO
Add keywords for these repositories:
- [x] https://github.com/agroportal/project-management, 
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/ 
- [x]  https://github.com/ontoportal-lirmm/ontologies_api/.
- [x] https://github.com/ontoportal/ontoportal-project, 
- [x] https://github.com/ontoportal/documentation, 
- [x] https://github.com/ontoportal/ontoportal_web_ui 
- [x]  https://github.com/ontoportal/ontologies_api.

**Comment by jonquet** [comment]
Are you refering to a a GitHub feature enabling to describe projects with "keywords" ? Can you point out?

**Comment by user34ngrau** [comment]
by keywords I mean the words that are affiliated to the project, that are represented in blue under the repository 
![image](https://github.com/agroportal/project-management/assets/135241416/0a37e219-97f5-4ffe-a8c0-8099da71517d)

**Comment by syphax-bouazzouni** [comment]
Done
