### ISSUE TITLE
Display Crop Ontology following TDv5 format allowing to distinguish the compsoition of a variable. 

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#501]
Crop Ontology has adopted the TDv5 format for years that represent Variable as a composition of a Trait, a Method and a Scale. 
When browsing/searching the ontologies users need to be able to the related variables of a given trait, method or scale ... and the other way arround, they need to see, when browsing a variable, the 3 component of that variable. 

If we take C0_356 as an example
For some reason, we have an issue related to OWL parsing that "prevent" the OWL restriction statments to be flatten. So inour case the relation is lost: https://github.com/agroportal/project-management/issues/499 

Assuming this is fixed (i.e., the flatten relation appears), this issue is about improving and customizing the UI for the Crop Ontology (more than 30 resources in AgroPortal and another 10 waiting).

For variable https://agroportal.lirmm.fr/ontologies/CO_356?p=classes&conceptid=https%3A%2F%2Fcropontology.org%2Frdf%2FCO_356%3A1000013

This is how Protégé does 
<img width="495" alt="Capture d’écran 2024-03-13 à 17 36 48" src="https://github.com/agroportal/project-management/assets/7379183/9fb88653-dbc5-46e3-8ef2-0d59f7a34730">
(this assume issue 499 above is completly fixed and we have the RDF restriction)

And the Variable somehow appear under the Trait (or Method or Scale) in the tree: 
<img width="232" alt="Capture d’écran 2024-03-13 à 17 38 11" src="https://github.com/agroportal/project-management/assets/7379183/a01e5e64-4cd7-4ece-948a-aedaf02d11d4">

The desired UI is the one from URGI browser: https://urgi.versailles.inra.fr/ephesis/ephesis/ontologyportal.do
<img width="884" alt="Capture d’écran 2024-03-13 à 17 38 57" src="https://github.com/agroportal/project-management/assets/7379183/062578cc-c8e0-4f43-b497-4679eac1dd1b">

Where for a given Variable (discovered thru the Trait only) one cleary see the Trait, Method and Scale involved.

**Comment by jonquet** [comment]
To address this FR we need to : 
- [ ] See why the flatten relationships are not in our backend. Parsing issue? 
- [x] Fix related issue https://github.com/agroportal/project-management/issues/500 
- [ ] Implement a way to distinguish crop ontologies following the TDv5 format in order to activate the specific UI. This is related maybe to #502 
- [ ] Certainly add the objects: https://cropontology.org/rdf/Method, https://cropontology.org/rdf/Scale, https://cropontology.org/rdf/Trait and https://cropontology.org/rdf/Variable to the model in order to be able to serve them with the API: /ontologies/CO_XX/variables etc. This might be related to https://github.com/ontoportal/ontoportal-project/issues/55 which suggests a generic way of implementing variable in OntoPortal.
- [ ] Revise the UI to see how to generate URGI like UI when we are browsing a Variable
- [ ] Revise the UI to add the Variable appear in the class hiearachy when we are browsing a Trait, Scale or Method

To be refine

**Comment by jonquet** [comment]
For information, this is how it looks on Cropontology.org: 
https://cropontology.org/term/CO_356:3000142
<img width="1157" alt="Capture d’écran 2024-03-13 à 18 04 03" src="https://github.com/agroportal/project-management/assets/7379183/82fef954-1358-4fb4-984b-6f70237fbc76">

**Comment by syphax-bouazzouni** [comment]
is this not specific to AgroPortal how to make it generic for ontoportal? @jonquet

**Comment by jonquet** [comment]
This issue and the TDv5 format is speciifc to AgroPortal. 
I would suggest we start answering this need , then connect that activity to the intern work related to scientific variables. Ultimaly OntoPortal shall be able to handle multiple scientific variable formats: 
https://docs.google.com/document/d/e/2PACX-1vR9xHLwDmL_bz13huU-cuudYixMnS1y8QDIz-m_tO3_jMct9nv8hqJZ8fJrUXtk3umUUulxk9zhN6Zm/pub
