### ISSUE TITLE
Release 2.7.5 bugs fixes plan  

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#508]
### Context
this issue lists the most bugs that have been raised recently, that will need to be fixed for the incoming release in May. 

Feel free to add other issues, the template to follow is:
```
{number} - {page}: {bug description}
{Screenshot}
```
### TODO
- [x] (critical) https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/578
- [ ] (critical) https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/577
- [x] (critical) https://github.com/agroportal/project-management/issues/481
- [ ] (critical) https://github.com/agroportal/project-management/issues/487
- [x] (critical) https://github.com/agroportal/project-management/issues/459
- [ ] (critical) https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/402
- [ ] (critical) https://github.com/agroportal/project-management/issues/486
- [ ] (critical) https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/557
- [ ] (not critical) https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/444
- [ ] (not critical) https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/437
- [ ] (not critical) https://github.com/agroportal/project-management/issues/484
- [ ] (not critical) https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/445
- [x] (not critical) https://github.com/agroportal/project-management/issues/493
- [x] (not critical) https://github.com/agroportal/project-management/issues/489
- [x] (not critical) https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/230
- [ ] (not critical) https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/527
- [ ] (not critical) https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/485

#### New bugs:
1- Summary page: when hovering the fair score tooltip it breaks ✅ 
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/eda94fa2-e816-4f78-bcff-0b91659aea90)
2- The warning and error icons are not in the good colors
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/75b94762-691e-48af-b402-2cb94de9afd5)
3- Summary page: in AGROVOC the subjects of the ontology need to be clickable and redirect to the ontology concept
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/d08c8a53-d001-4130-8f63-1a46447552eb)
5- Recommender page: the ontologies links redirect to API instead of the UI  ✅ 
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/c9a045d7-fec9-4220-a266-30cabd5b2da9)
6- Concept page: Notes buttons are too big ✅ 
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/7ba6ebd0-8816-499e-901e-05da8bc84b71)
7- Edit submission/ontology: The component of editing a single agent UX is not good 
![image](https://github.com/agroportal/project-management/assets/29259906/c26583d0-433e-4adc-bccb-0407dafbba92)

### Not fixed:

See issues screnshots in https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/555
8- Summary page: When text is truncated we can’t see the hidden part on hover (critical)
17 - Annotator: When “Fast Context”, is selected the page returns an error (critical)
23- Recommender: using keywords with the sample text; shows No results found (critical)
21- Recommender: Annotation button text is not aligned (not-critical)
28- Concepts tree views filters, these alerts can be re-arranged (alerts than the select) (not-critical)

**Comment by jonquet** [comment]
You mean release 2.7.4 ?

**Comment by syphax-bouazzouni** [comment]
> You mean release 2.7.4?

No I meant 2.7.5, the next one

**Comment by syphax-bouazzouni** [comment]
Moved to #535  and #537 
* https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/577
* https://github.com/agroportal/project-management/issues/487
* https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/402
* https://github.com/agroportal/project-management/issues/486
* https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/557
* https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/444
* https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/437
* https://github.com/agroportal/project-management/issues/484
* https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/445
* https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/485


2- The warning and error icons are not in the good colors
![image](https://github.com/agroportal/project-management/assets/29259906/5921d6ca-2a9d-43fb-b148-a237f7556fa6)
3- Summary page: in AGROVOC the subjects of the ontology need to be clickable and redirect to the ontology concept
![image](https://github.com/agroportal/project-management/assets/29259906/fdc0de34-c343-4d5e-9c45-5b465da02f03)
7- Edit submission/ontology: The component of editing a single agent UX is not good
![image](https://github.com/agroportal/project-management/assets/29259906/43e4c702-eec0-427e-ac18-7042a25107d4)
8- Summary page: When text is truncated we can’t see the hidden part on hover (critical)
