### ISSUE TITLE
Portal metadata root endpoint

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#592]
### TODO

- [x] Define which properties to set a portal metadata 
- [x] Update the root endpoint to display the portal metadata
- [x] Update the home page other portals section to display portal metadata as a tooltip 
![image](https://github.com/user-attachments/assets/ae369884-1aa3-4c0c-93b2-12390021ac43)

**Comment by jonquet** [comment]
We need to adopt MOD3 for this. So a "portal" should be a mod:SemanticArtefactCatalogue

The list of properties to implement for a mod:SemanticArtefactCatalogue is here: https://docs.google.com/spreadsheets/d/1APdKgSCFKlM8Wxi4WCl_weaiU7x3I-xW6cgg-RS3_zw/edit?gid=1638855124#gid=1638855124 
(filter column L on true)
MOD3.2 is available here: https://github.com/FAIR-IMPACT/MOD

Consequently, the information we see in the "example" tooltip ilsutrated above are coming from the following properties: 
- foaf:logo
- dcterms:title
- mod:numberOfArtefacts
- dcterms:description
- foaf:fundedBy 

Note that: 
- MOD3 does not provide the list of portal "federated with" this property would have to be implemented in the bpm namesapce. 
- MOD3 specifcies the range of foaf:fundedBy as a owl:Thing so its ok to define our own small structure (JSON emebedded object) that woul contains nale/URL/logo as we probably have in the config file

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/744
