### ISSUE TITLE
Do a script to migrate data from 4store to the Virtuoso or Algregraph Triple-store

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#607]
### Context
See https://github.com/agroportal/project-management/issues/229

### TODO

- [ ] Create a unified script to import or export data from 4store to Virtuoso or Algregraph (@syphax-bouazzouni)
- [ ] Create a documentation  (@syphax-bouazzouni)
- [ ] Test it in Testportal (@syphax-bouazzouni )
- [ ] Test it in Stageportal (@syphax-bouazzouni )
- [ ] Do it in production for BioDivPortal and EcoPortal (@syphax-bouazzouni)
- [ ] Do it in production for AstroPortal (@imadbourouche )
- [ ] Do it in production for LovPortal (@muhammedBkf)
- [ ] Do it in production for AgroPortal (@syphax-bouazzouni)

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/ncbo_cron/pull/31 and documentation produced here: https://doc.jonquetlab.lirmm.fr/share/7b7ecb64-9842-416b-a513-9a5cd251d59d
