### ISSUE TITLE
Migrate to Ruby 3

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#609]
### TODO

- [x] UI (done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/930)
- [x] API CLIENT
- [x] API(https://github.com/ontoportal-lirmm/ontologies_api/pull/121)
- [x] CRON(https://github.com/ontoportal-lirmm/ncbo_cron/pull/32)
- [x] OLD (https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/189)
- [x] GOO (https://github.com/ontoportal-lirmm/goo/pull/74)
- [x] SPARQL CLIENT(test are already passing https://github.com/ontoportal-lirmm/sparql-client/actions/runs/12939471494/job/36091794523)

### Related work done by NCBO
- https://github.com/ncbo/ontologies_linked_data/pull/214
- https://github.com/ncbo/ontologies_api/pull/159
- https://github.com/ncbo/ncbo_annotator/pull/34
- https://github.com/ncbo/ncbo_ontology_recommender/pull/22
- https://github.com/ncbo/ncbo_cron/pull/84
- https://github.com/ncbo/bioportal_web_ui/pull/284

**Comment by syphax-bouazzouni** [comment]
Related https://github.com/ontoportal-lirmm/ontologies_api/pull/102

**Comment by syphax-bouazzouni** [comment]
Done
