### ISSUE TITLE
Deployment of LovPortal: Migrate LOV to OntoPortal 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#610]
### Context

The Linked Open Vocabularies (LOV) portal, launched in 2011 as part of the W3C's Semantic Web activity, serves as a curated repository for reusable vocabularies in the Semantic Web and Linked Data contexts. It encourages community contributions and provides advanced search functionalities, allowing users to filter and discover vocabularies easily. Each entry includes metadata, usage examples, and documentation links. LOV plays a vital role in promoting standardization, interoperability, and data sharing by offering a valuable resource for developers and researchers seeking established vocabularies.

### Goals

- Have a portal called LovPortal using the latest version of OntoPortal deployed  and containing most of the vocabularies of https://lov.linkeddata.es/dataset/lov/vocabs, including all the versions and metadata. In some cases, some vocabularies will be uploaded in another ontology repository of the OntoPortal Alliance.
- Have an automatic script that will fetch a vocabulary from LOV to an OntoPortal instance including its versions and metadata, either on demand or run automatically when a new vocabulary or version is detected. 

French description of the "topic" is here: https://docs.google.com/document/d/e/2PACX-1vRkZxbzjCTYYowCpKezbCcct0hvmOnsdBD83_ny_8oii9OAI-2kKLvBYZzth9QFMmoe1PXhp9pLgMrS/pub

### TODO

- [x] #611
- [x] #612
- [ ] Define a correspondence table between the LOV and OntoPortal metadata model
- [ ] Deploy LovPortal on the LIRMM server
- [ ] Do a script in ruby doing  OntoPortal API post request to submit a new vocabulary or add a new version, having as arguments the `source` (a link to an lov vocabulary) and `target`(a link to an ontoportal API instance) and `apikey`

![image](https://github.com/user-attachments/assets/557b7cda-d185-46eb-9f10-4805e7905295)

### References 

- Lov UI https://lov.linkeddata.es/dataset/lov
- Lov API documentation https://lov.linkeddata.es/dataset/lov/api
- Lov documentation https://lov.linkeddata.es/dataset/lov/about 
- Ontoportal API documentation https://data.agroportal.lirmm.fr/documentation 
- Ontoportal API HTTP request examples https://doc.jonquetlab.lirmm.fr/share/06f7bea3-eeaf-4fc4-a751-3b928bd961b7

**Comment by jonquet** [comment]
Reference GSheet to manage the dispatch to LovPortal and other OntoPortals: https://docs.google.com/spreadsheets/d/1fR9faeCUTAlqwR6sdNrmw1gFQnsWX00-UhpTEQ9Zimo

We are going to need a collaborative look at this spreadsheet at least by the portals concerned: 
- [ ] Contact the portal providers to ask them to validate/accept and complete the dispatch of LOV vocabularies with respect to the portal they are running
- [ ] Validate the process with the current LOV team

**Comment by syphax-bouazzouni** [comment]
done https://lovportal.lirmm.fr
