### ISSUE TITLE
stabilize better our docker tests 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#623]
### Context
Our tests regularly fail because the docker image is not working or had any issue in the docker-compose files (e.g https://github.com/ontoportal-lirmm/ontologies_api/commit/ce6b2077cc7801daef44af25e53272eddf2f8c9a)

### TODO

- [ ] Add a production service to https://github.com/ontoportal-lirmm/ontologies_api/blob/master/docker-compose.yml to separate the dev and prod configuration
- [ ] Add a production service to https://github.com/ontoportal-lirmm/ncbo_cron/blob/master/docker-compose.yml  to separate the dev and prod configuration
- [ ] Do not build the images if backend tests are failing 
- [ ] Do not build stage and tests images
- [ ] Do not build the ARM version for now (until we have maybe Mac m1)
